kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  labels:
    environment: production
data:
  CKAN_SQLALCHEMY_URL: postgresql://ckan:password@10.0.2.2:5432/ckan
  CKAN_DATASTORE_WRITE_URL: postgresql://ckan:password@10.0.2.2:5432/datastore
  CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:password@10.0.2.2:5432/datstore
  CKAN_SOLR_URL: http://solr:8983/solr/ckan
  CKAN_REDIS_URL: redis://redis:6379/1
  CKAN_DATAPUSHER_URL: http://datapusher:8800
  CKAN_SITE_URL: '' 
  POSTGRES_PASSWORD: password
  DS_RO_PASS: password