apiVersion: v1
kind: Service
metadata:
  name: datapusher
  labels:
    app: datapusher
    environment: production
spec:
  type: NodePort
  ports:
    - port: 8800
      targetPort: 8800
  selector:
    app: datapusher
    environment: production
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datapusher
  labels:
    app: datapusher
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datapusher
        environment: production
    spec:
      containers:
        - name: datapusher
          image: clementmouchet/datapusher
          ports:
            - containerPort: 8800