apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    environment: production
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    environment: production
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        environment: production
    spec:
      containers:
        - name: redis
          image: redis:latest
          volumeMounts:
            - mountPath: /data
              name: redis-storage
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-storage
          emptyDir: {}
