version: '3'
services:

  # docker-compose build && docker-compose up
  # If you experience problems with the CKAN container not being
  # able to connect to the DB, then most likely the DB has not
  # started up quickly enough. Just do "docker-compose up ckan"
  # again to retry
  ckan:
    container_name: ckan
    build: ../../
    links:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    environment:
      - SITE_TITLE=thedataplace
      - CKAN_SQLALCHEMY_URL=postgres://ckan:ckan@db:5432/ckan
      - CKAN_SOLR_URL=http://solr:8983/solr
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
    command: ["/usr/lib/ckan/default/bin/uwsgi", "--ini-paste", "/etc/ckan/default/ckan.ini", "--chmod-socket=666", "--socket=0.0.0.0:3031", "--master", "--processes=1"]

  db:
    container_name: db
    build: postgresql/
    
  solr:
    container_name: solr
    build: solr/
      
  redis:
    container_name: redis
    image: redis:latest

  nginx:
    container_name: nginx
    build: nginx/
    restart: always
    ports:
      - 8080:80
    links:
      - ckan

